# Generated by Django 6.1 on 2026-08-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dispatcher',
            fields=[
                ('dispatcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatcher_name', models.CharField(max_length=100)),
                ('dispatcher_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='retailer',
            fields=[
                ('retailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('retailer_name', models.CharField(max_length=100)),
                ('retailer_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='rider',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False)),
                ('rider_name', models.CharField(max_length=100)),
                ('rider_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='confirmation',
            fields=[
                ('confirmation_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.assignment')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.delivery_request')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='delivery_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.delivery_request'),
        ),
        migrations.AddField(
            model_name='delivery_request',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.dispatcher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.dispatcher'),
        ),
        migrations.AddField(
            model_name='delivery_request',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.retailer'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.rider'),
        ),
    ]
