# Generated by Django 6.1 on 2026-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_delivery_request_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='retailer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
