# Generated by Django 6.1 on 2026-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_request',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
