# Generated by Django 6.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_alter_retailer_retailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_request',
            name='delivery_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('ASSIGNED', 'Assigned'),
                    ('PICKED', 'Picked'),
                    ('DELIVERED', 'Delivered'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='delivery_request',
            name='dispatcher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to='sprint.dispatcher',
            ),
        ),
    ]
